apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-container
        image: gcr.io/sinuous-ally-322609/dashboard:v1
        ports:
        - containerPort: 3000
          protocol: TCP
      
